version: "3.9"

services:
  web:
    container_name: elixir
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    links:
      - db
    # env_file:
    #   - .envrc
    environment:
      - FLY_APP_NAME=test
      - DATABASE_URL=ecto://postgres:postgres@db:5432/ttc_alerts_dev
      - SECRET_KEY_BASE=iShYUhAk+q9rc63MPD11cXqOHR1Gb3bOBRefEbHzl2IzhdMfffYQ6RFuyXzuJJuf
  db:
    container_name: db
    image: "postgres:12"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ttc_alerts_dev
    volumes:
      - pgdata1:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata1: {}
